#!/bin/bash
set -e

DEST=$1
BINARY_NAME="docker-$VERSION"
BINARY_EXTENSION="$(binary_extension)"
BINARY_FULLNAME="$BINARY_NAME$BINARY_EXTENSION"

# Cygdrive paths don't play well with go build -o.
if [[ "$(uname -s)" == CYGWIN* ]]; then
	DEST=$(cygpath -mw $DEST)
fi

source "$(dirname "$BASH_SOURCE")/.go-autogen"

if [ -z "$USE_GCCGO" ]; then
	go build \
		-o "$DEST/$BINARY_FULLNAME" \
		"${BUILDFLAGS[@]}" \
		-ldflags "
			$LDFLAGS
			$LDFLAGS_STATIC_DOCKER
		" \
		./docker
else
	go build -compiler gccgo \
		-o "$DEST/docker-$VERSION" \
		"${BUILDFLAGS[@]}" \
		-gccgoflags "
			$EXTLDFLAGS_STATIC_DOCKER
			-ldl
			-lselinux
			-lsepol
			-lpcre
		" \
		./docker
fi

echo "Created binary: $DEST/$BINARY_FULLNAME"
ln -sf "$BINARY_FULLNAME" "$DEST/docker$BINARY_EXTENSION"

hash_files "$DEST/$BINARY_FULLNAME"
